### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by Yexiansen66** [AsadUrRehmanCs111/JavaScript-Projects#1]
The function completeTodo
   list[element.id].done = list[element.id].done ? true : false;
should be
  list[element.id].done = list[element.id].done ? false : true;
Is it right?

**Comment by AsadUrRehmanCs111** [comment]
It Works. But if You delete the item without making it done and refresh the browser it will not show... But when You Use this list[element.id].done = list[element.id].done ? true : false; the item will show up.
